version: '3.8'

services:

  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:6
    ports:
      - '6379:6379'
    #command: redis-server --requirepass ${REDIS_PASSWORD}
    #environment:
    #  REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: unless-stopped

  backend:
    container_name: backend
    build: ./backend
    #image: anrysys/anry-full-stack-next-backend:latest
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    command: >
      sh -c "
        ./migrations/apply_migrations.sh &&
        npm start
      "
  frontend:
    container_name: frontend
    build: ./frontend
    #image: anrysys/anry-full-stack-next-frontend:latest
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      BACKEND_HOST: backend


volumes:
  pgdata: